### ISSUE TITLE
Unable to set Content-Type request header

### ISSUE THREAD

**Issue by ccarmannt** [QualitySoftwareMatters/James.Testing#16]
I need to set the Content-Type header on a request:

            request.WithHeaders(new { Content_Type = "text/plain" });

But the call above results in the following exception:

````
System.InvalidOperationException : Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at James.Testing.Rest.HttpClientExtensions.AddHeaders(HttpClient client, Object headers)
   at James.Testing.Rest.RequestBase`2.Execute()
   at James.Testing.Rest.Request.Execute[TResponse,TError](IRequest`2 request)
   at James.Testing.Rest.Request.Post[TBody,TResponse,TError](TBody body)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at James.Testing.Rest.Request.Post(Object body)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
````

I've attempted to find another method within the James.Testing.Rest package that can be used for this, but without success...

**Comment by toddmeinershagen** [comment]
So - the library currently makes an assumption that posts are going to use the "application/json" content type.  

Would you send me an example of the what is being passed in the Post(object body) method call and what you expect to come back in the body?

**Comment by ccarmannt** [comment]
I don't know yet exactly what is going to be passed in the body. All I have is a swagger document that indicates we need to send some sort of file contents with a Content-Type of "multipart/form-data".
